### ISSUE TITLE
xgboost package is not recorded in renv lockfile

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/PatientLevelPredictionModule#13]
The package `xgboost` is a suggested package for `PatientLevelPrediction` (https://github.com/OHDSI/PatientLevelPrediction/blob/86930edfdaf38fd11960435427ffc95081dd192a/DESCRIPTION#L71) and required for training Gradient Boosting models. It currently is not recorded in the renv lockfile, but I believe it should be.

**Comment by anthonysena** [comment]
Closing as this was added via #15
